package io.github.arun0009.pulse.slo;

import java.time.Duration;
import java.util.List;
import java.util.Locale;

/**
 * Renders {@link SloProperties.Objective} declarations into a Prometheus-compatible
 * {@code PrometheusRule} document — recording rules plus multi-window, multi-burn-rate
 * alerts following the Google SRE workbook pattern.
 *
 * <p>The output is plain YAML. It is consumed by:
 *
 * <ul>
 *   <li>The {@code /actuator/pulse/slo} endpoint, where ops can {@code curl … | kubectl apply -f -}.
 *   <li>The Pulse build pipeline / CI, which can dump it to a file for review on every merge.
 * </ul>
 *
 * <p>Two SLI families are supported, mirroring the real-world fast-path:
 *
 * <ul>
 *   <li>{@code availability} — non-5xx responses divided by total responses on
 *       {@code http_server_requests_seconds_count}.
 *   <li>{@code latency} — fraction of requests under a threshold, derived from
 *       {@code http_server_requests_seconds_bucket} via {@code histogram_quantile}-equivalent
 *       direct bucket counting.
 * </ul>
 *
 * <p>Burn rates and windows follow the SRE workbook recommendations:
 *
 * <ul>
 *   <li>Page on a 14.4× burn over 1h (roughly: 2% of monthly budget consumed in 1h).
 *   <li>Ticket on a 6× burn over 6h (roughly: 5% of monthly budget consumed in 6h).
 * </ul>
 */
public final class SloRuleGenerator {

    private static final double FAST_BURN_RATE = 14.4;
    private static final double SLOW_BURN_RATE = 6.0;
    private static final Duration FAST_WINDOW = Duration.ofHours(1);
    private static final Duration SLOW_WINDOW = Duration.ofHours(6);

    private final SloProperties config;
    private final String serviceName;

    public SloRuleGenerator(SloProperties config, String serviceName) {
        this.config = config;
        this.serviceName = serviceName;
    }

    /**
     * Returns a complete PrometheusRule YAML document. If no objectives are declared, returns a
     * header-only document (still valid YAML, makes the endpoint always parse cleanly).
     *
     * @return the rendered YAML document.
     */
    public String render() {
        StringBuilder yaml = new StringBuilder();
        yaml.append("# Generated by Pulse — io.github.arun0009.pulse.slo.SloRuleGenerator\n");
        yaml.append("# Source of truth: pulse.slo.objectives in your application.yml\n");
        yaml.append("# Apply with:  curl -s http://<host>/actuator/pulse/slo | kubectl apply -f -\n");
        yaml.append("apiVersion: monitoring.coreos.com/v1\n");
        yaml.append("kind: PrometheusRule\n");
        yaml.append("metadata:\n");
        yaml.append("  name: pulse-slo-").append(safe(serviceName)).append("\n");
        yaml.append("  labels:\n");
        yaml.append("    app.kubernetes.io/managed-by: pulse\n");
        yaml.append("    pulse.slo/service: ").append(safe(serviceName)).append("\n");
        yaml.append("spec:\n");
        yaml.append("  groups:\n");

        List<SloProperties.Objective> objectives = config.objectives();
        if (objectives.isEmpty()) {
            yaml.append("    # No SLOs declared. Add some under pulse.slo.objectives in application.yml.\n");
            yaml.append("    []\n");
            return yaml.toString();
        }

        for (SloProperties.Objective o : objectives) {
            renderObjective(yaml, o);
        }
        return yaml.toString();
    }

    private void renderObjective(StringBuilder yaml, SloProperties.Objective o) {
        String name = safe(o.name());
        String sli = o.sli().toLowerCase(Locale.ROOT);
        String filterClause = buildFilterClause(o);

        String numerator;
        String denominator;
        String description;

        if ("latency".equals(sli)) {
            if (o.threshold() == null) {
                throw new IllegalArgumentException("Pulse SLO '" + o.name()
                        + "' has sli=latency but no threshold; set pulse.slo.objectives[].threshold");
            }
            double thresholdSeconds = o.threshold().toMillis() / 1000.0;
            numerator = "sum(rate(http_server_requests_seconds_bucket{le=\"" + formatBucket(thresholdSeconds) + "\""
                    + maybeComma(filterClause) + "}[%WINDOW%]))";
            denominator = "sum(rate(http_server_requests_seconds_count{" + filterClause + "}[%WINDOW%]))";
            description = "fraction of requests under " + o.threshold();
        } else {
            // availability is the default
            numerator = "sum(rate(http_server_requests_seconds_count{status!~\"5..\"" + maybeComma(filterClause)
                    + "}[%WINDOW%]))";
            denominator = "sum(rate(http_server_requests_seconds_count{" + filterClause + "}[%WINDOW%]))";
            description = "non-5xx response fraction";
        }

        yaml.append("    - name: ").append(name).append("-recording\n");
        yaml.append("      interval: 30s\n");
        yaml.append("      rules:\n");
        for (Duration window : List.of(FAST_WINDOW, SLOW_WINDOW)) {
            String w = formatWindow(window);
            yaml.append("        - record: pulse:slo:")
                    .append(name)
                    .append(":good_ratio:")
                    .append(w)
                    .append("\n");
            yaml.append("          expr: |\n");
            yaml.append("            (")
                    .append(numerator.replace("%WINDOW%", w))
                    .append(") / (")
                    .append(denominator.replace("%WINDOW%", w))
                    .append(")\n");
        }

        yaml.append("    - name: ").append(name).append("-alerts\n");
        yaml.append("      rules:\n");
        renderBurnAlert(yaml, name, o, FAST_BURN_RATE, FAST_WINDOW, "page", description);
        renderBurnAlert(yaml, name, o, SLOW_BURN_RATE, SLOW_WINDOW, "ticket", description);
    }

    private void renderBurnAlert(
            StringBuilder yaml,
            String name,
            SloProperties.Objective o,
            double burnRate,
            Duration window,
            String severity,
            String description) {
        String w = formatWindow(window);
        double errorBudget = 1.0 - o.target();
        double burnThreshold = burnRate * errorBudget;

        yaml.append("        - alert: PulseSloBurn_")
                .append(name)
                .append("_")
                .append(severity)
                .append("\n");
        yaml.append("          expr: |\n");
        yaml.append("            (1 - pulse:slo:")
                .append(name)
                .append(":good_ratio:")
                .append(w)
                .append(") > ")
                .append(formatNumber(burnThreshold))
                .append("\n");
        yaml.append("          for: 5m\n");
        yaml.append("          labels:\n");
        yaml.append("            severity: ").append(severity).append("\n");
        yaml.append("            slo: ").append(name).append("\n");
        yaml.append("            burn_rate: \"").append(formatNumber(burnRate)).append("\"\n");
        yaml.append("          annotations:\n");
        yaml.append("            summary: \"SLO burn for ")
                .append(name)
                .append(" — ")
                .append(formatNumber(burnRate))
                .append("× error budget over ")
                .append(w)
                .append("\"\n");
        yaml.append("            description: \"")
                .append(description)
                .append(" (target ")
                .append(formatNumber(o.target() * 100))
                .append("%) is burning at ")
                .append(formatNumber(burnRate))
                .append("× the sustainable rate. At this pace the monthly budget is exhausted in ")
                .append(formatBudgetBurn(burnRate))
                .append(".\"\n");
    }

    private String buildFilterClause(SloProperties.Objective o) {
        // Always scope to the application; consumers can add more filters in YAML.
        StringBuilder sb =
                new StringBuilder("application=\"").append(safe(serviceName)).append("\"");
        for (String f : o.filters()) {
            // f is expected as raw label-matcher fragments like   uri="/orders"
            String trimmed = f.trim();
            if (trimmed.isEmpty()) continue;
            sb.append(",").append(trimmed);
        }
        return sb.toString();
    }

    private static String maybeComma(String filter) {
        return filter.isEmpty() ? "" : "," + filter;
    }

    private static String safe(String s) {
        return s.replaceAll("[^A-Za-z0-9_.-]", "-");
    }

    private static String formatWindow(Duration w) {
        long hours = w.toHours();
        return hours + "h";
    }

    private static String formatBucket(double seconds) {
        // Match the Pulse default bucket boundaries; if a user uses a non-standard threshold the
        // bucket count is still meaningful (Prometheus will pick the closest le=).
        // Strip trailing zeros so 500ms renders as "0.5" not "0.500", matching how Micrometer
        // labels its le= buckets.
        String s = String.format(Locale.ROOT, "%.3f", seconds);
        if (s.contains(".")) {
            s = s.replaceAll("0+$", "").replaceAll("\\.$", "");
        }
        return s;
    }

    private static String formatNumber(double d) {
        if (d == Math.floor(d)) return String.format(Locale.ROOT, "%.1f", d);
        return String.format(Locale.ROOT, "%.4f", d);
    }

    private static String formatBudgetBurn(double burnRate) {
        // 30 days / burnRate gives "days to exhaustion at this rate".
        double days = 30.0 / burnRate;
        if (days < 1) return String.format(Locale.ROOT, "%.1f hours", days * 24);
        return String.format(Locale.ROOT, "%.1f days", days);
    }
}
