package io.github.arun0009.pulse.logging;

import org.jspecify.annotations.Nullable;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.env.EnvironmentPostProcessor;
import org.springframework.core.Ordered;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.core.io.support.SpringFactoriesLoader;

import java.io.IOException;
import java.io.InputStream;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.function.Function;

/**
 * Seeds JVM system properties so the log4j2 JSON layout can stamp <em>every</em> log line —
 * including pre-Spring-boot lines from background threads — with the build version and commit
 * hash, no per-thread MDC plumbing required.
 *
 * <p>Runs as an {@link EnvironmentPostProcessor} so it executes before any {@code @Bean} is
 * created and before most application logging starts. The system properties this sets are
 * referenced by {@code pulse-json-layout.json} as {@code ${sys:pulse.app.version:-unknown}}
 * and {@code ${sys:pulse.build.commit:-unknown}}.
 *
 * <h2>Resolution chain</h2>
 *
 * Pulse cannot put values <em>into</em> your JAR or environment — Maven plugins are not
 * transitive, and a Fargate task that downloads a pre-built JAR has no git context. What
 * Pulse <em>can</em> do is read whichever of these is present at runtime, in priority order
 * (first non-empty wins per key):
 *
 * <ol>
 *   <li><b>JVM system property</b> — operator override (e.g. {@code -Dpulse.app.version=1.4.2}).
 *       Always wins.</li>
 *   <li><b>Classpath {@code META-INF/build-info.properties} / {@code git.properties}</b> —
 *       baked into the JAR at build time. <em>Recommended for build-once-deploy-many pipelines
 *       (Artifactory → Docker → Fargate / EKS)</em> because the values travel inside the JAR
 *       through any pipeline. Generated by Spring Boot's {@code build-info} goal and the
 *       {@code git-commit-id-maven-plugin} (see README for the 25-line snippet).</li>
 *   <li><b>{@code OTEL_RESOURCE_ATTRIBUTES} env var</b> — OTel-standard. Reads
 *       {@code service.version} for app version, and {@code deployment.commit} or
 *       {@code vcs.commit.id} for commit hash. Common when your platform (K8s, CodeDeploy,
 *       Fargate task definition) templates the values in.</li>
 *   <li><b>Common CI/runtime env vars</b> — {@code BUILD_VERSION}, {@code APP_VERSION},
 *       {@code IMAGE_TAG} for version; {@code GIT_COMMIT}, {@code GITHUB_SHA},
 *       {@code CI_COMMIT_SHA}, {@code COMMIT_SHA}, {@code BITBUCKET_COMMIT},
 *       {@code SOURCE_VERSION} for commit. Useful in CI smoke runs and when the deploy
 *       pipeline threads them into the container env.</li>
 *   <li><b>Main class JAR manifest {@code Implementation-Version}</b> — Spring Boot's maven
 *       plugin always writes this from your pom version, so {@code app.version} is free with
 *       <em>zero</em> extra config (commit hash is not).</li>
 *   <li><b>Fallback</b> — the system property is left unset and the layout substitutes
 *       {@code "unknown"}.</li>
 * </ol>
 *
 * <h2>Why a system property and not MDC</h2>
 *
 * MDC is per-thread; build version/commit are per-process. Using JVM system properties means
 * the values appear on logs from every thread (including background pools that started before
 * Spring did) without any per-call setup.
 */
public final class PulseLoggingEnvironmentPostProcessor implements EnvironmentPostProcessor, Ordered {

    static final String VERSION_SYS_PROP = "pulse.app.version";
    static final String COMMIT_SYS_PROP = "pulse.build.commit";

    /**
     * System-property prefix Pulse uses for resource attributes. The Log4j2 JSON layout and the
     * Logback encoder both substitute these via {@code ${sys:pulse.host.name:-unknown}} and
     * friends, so the keys are the OTel semantic-convention name with this prefix.
     */
    static final String RESOURCE_ATTRIBUTE_SYS_PROP_PREFIX = "pulse.";

    static final String BUILD_INFO_RESOURCE = "META-INF/build-info.properties";
    static final String GIT_PROPERTIES_RESOURCE = "git.properties";
    static final String OTEL_RESOURCE_ATTRIBUTES_ENV = "OTEL_RESOURCE_ATTRIBUTES";

    /** Env var names tried in order for {@code app.version}. */
    static final List<String> VERSION_ENV_VARS = List.of("BUILD_VERSION", "APP_VERSION", "IMAGE_TAG");

    /** Env var names tried in order for {@code build.commit} (values are abbreviated to 8 chars). */
    static final List<String> COMMIT_ENV_VARS =
            List.of("GIT_COMMIT", "GITHUB_SHA", "CI_COMMIT_SHA", "COMMIT_SHA", "BITBUCKET_COMMIT", "SOURCE_VERSION");

    /** OTel resource-attribute keys checked for the commit hash. */
    static final List<String> OTEL_COMMIT_KEYS = List.of("deployment.commit", "vcs.commit.id");

    private static final int SHORT_SHA_LENGTH = 8;

    private final Function<String, @Nullable String> envLookup;
    private final ClassLoader classLoader;
    private final ResourceAttributeResolver resourceAttributeResolver;

    public PulseLoggingEnvironmentPostProcessor() {
        this(System::getenv, defaultClassLoader(), discoverResolver(defaultClassLoader()));
    }

    // Package-private for tests.
    PulseLoggingEnvironmentPostProcessor(
            Function<String, @Nullable String> envLookup,
            ClassLoader classLoader,
            ResourceAttributeResolver resourceAttributeResolver) {
        this.envLookup = envLookup;
        this.classLoader = classLoader;
        this.resourceAttributeResolver = resourceAttributeResolver;
    }

    /**
     * Discovers a user-supplied {@link ResourceAttributeResolver} or {@link HostNameProvider}
     * via Spring's {@code spring.factories} mechanism so extensions work even at this stage
     * (before any {@code @Bean} exists). Resolution order:
     *
     * <ol>
     *   <li>If the user registered a {@code ResourceAttributeResolver} subclass, use that
     *       (full replacement of the detection chain).</li>
     *   <li>Otherwise, build a stock resolver wrapping the user's {@code HostNameProvider}
     *       implementation if present.</li>
     *   <li>Otherwise, build a stock resolver with all defaults.</li>
     * </ol>
     */
    private static ResourceAttributeResolver discoverResolver(ClassLoader classLoader) {
        SpringFactoriesLoader factories =
                SpringFactoriesLoader.forResourceLocation("META-INF/spring.factories", classLoader);
        List<ResourceAttributeResolver> resolvers = factories.load(ResourceAttributeResolver.class);
        if (!resolvers.isEmpty()) {
            return resolvers.get(0);
        }
        List<HostNameProvider> hostProviders = factories.load(HostNameProvider.class);
        if (!hostProviders.isEmpty()) {
            return new ResourceAttributeResolver(hostProviders.get(0));
        }
        return new ResourceAttributeResolver();
    }

    @Override
    public int getOrder() {
        // Run before LoggingSystem is initialised so values are present before the first
        // log line that references them is emitted.
        return Ordered.HIGHEST_PRECEDENCE + 5;
    }

    @Override
    public void postProcessEnvironment(ConfigurableEnvironment environment, SpringApplication application) {
        seedIfAbsent(VERSION_SYS_PROP, () -> resolveVersion(application));
        seedIfAbsent(COMMIT_SYS_PROP, this::resolveCommit);
        seedResourceAttributes();
    }

    /**
     * Resolves OTel resource attributes (host, container, k8s, cloud) once at startup and seeds
     * each detected value as {@code pulse.<otel.attribute.name>} so the JSON layouts can stamp
     * them on every log line. Undetected attributes are left unset so the layout substitutes its
     * configured default ({@code "unknown"}) — we never want to falsely label, say, a developer's
     * laptop as {@code k8s.pod.name=arun-mbp}.
     */
    private void seedResourceAttributes() {
        for (Map.Entry<String, String> entry :
                resourceAttributeResolver.resolveAll().entrySet()) {
            seedIfAbsent(RESOURCE_ATTRIBUTE_SYS_PROP_PREFIX + entry.getKey(), entry::getValue);
        }
    }

    private static void seedIfAbsent(String systemProperty, java.util.function.Supplier<@Nullable String> resolver) {
        if (System.getProperty(systemProperty) != null) {
            return;
        }
        String value = resolver.get();
        if (value != null && !value.isBlank()) {
            System.setProperty(systemProperty, value);
        }
    }

    @Nullable String resolveVersion(SpringApplication application) {
        String value = fromClasspathProperties(BUILD_INFO_RESOURCE, "build.version");
        if (value != null) return value;

        value = fromOtelResourceAttribute("service.version");
        if (value != null) return value;

        value = fromEnvVars(VERSION_ENV_VARS);
        if (value != null) return value;

        return fromMainClassManifest(application);
    }

    @Nullable String resolveCommit() {
        String value = fromClasspathProperties(GIT_PROPERTIES_RESOURCE, "git.commit.id.abbrev");
        if (value != null) return value;

        for (String key : OTEL_COMMIT_KEYS) {
            value = fromOtelResourceAttribute(key);
            if (value != null) return abbreviate(value);
        }

        value = fromEnvVars(COMMIT_ENV_VARS);
        if (value != null) return abbreviate(value);

        return null;
    }

    @Nullable private String fromClasspathProperties(String resource, String key) {
        try (InputStream in = classLoader.getResourceAsStream(resource)) {
            if (in == null) return null;
            Properties properties = new Properties();
            properties.load(in);
            String value = properties.getProperty(key);
            return (value != null && !value.isBlank()) ? value : null;
        } catch (IOException ignored) {
            // Classpath resource unreadable — fall through to the next source.
            return null;
        }
    }

    @Nullable private String fromOtelResourceAttribute(String attributeKey) {
        String raw = envLookup.apply(OTEL_RESOURCE_ATTRIBUTES_ENV);
        return parseOtelAttribute(raw, attributeKey);
    }

    @Nullable private String fromEnvVars(List<String> names) {
        for (String name : names) {
            String value = envLookup.apply(name);
            if (value != null && !value.isBlank()) return value;
        }
        return null;
    }

    /**
     * Reads {@code Implementation-Version} from the manifest of the JAR containing the
     * application's main class. Returns {@code null} when running from {@code target/classes}
     * (IDE / test launches) or when the manifest is absent.
     */
    @Nullable private static String fromMainClassManifest(SpringApplication application) {
        Class<?> mainClass = application.getMainApplicationClass();
        if (mainClass == null) return null;
        Package pkg = mainClass.getPackage();
        if (pkg == null) return null;
        String version = pkg.getImplementationVersion();
        return (version != null && !version.isBlank()) ? version : null;
    }

    /**
     * Parses a single attribute out of an {@code OTEL_RESOURCE_ATTRIBUTES} value of the form
     * {@code key1=value1,key2=value2}. Per the OTel spec, values are URL-encoded; we decode
     * defensively but tolerate already-decoded values.
     */
    @Nullable static String parseOtelAttribute(@Nullable String raw, String attributeKey) {
        if (raw == null || raw.isBlank()) return null;
        for (String pair : raw.split(",")) {
            int eq = pair.indexOf('=');
            if (eq <= 0) continue;
            String k = pair.substring(0, eq).trim();
            if (!k.equals(attributeKey)) continue;
            String v = pair.substring(eq + 1).trim();
            if (v.isEmpty()) return null;
            try {
                return URLDecoder.decode(v, StandardCharsets.UTF_8);
            } catch (IllegalArgumentException ignored) {
                return v;
            }
        }
        return null;
    }

    private static String abbreviate(String sha) {
        return sha.length() <= SHORT_SHA_LENGTH ? sha : sha.substring(0, SHORT_SHA_LENGTH);
    }

    private static ClassLoader defaultClassLoader() {
        ClassLoader cl = Thread.currentThread().getContextClassLoader();
        if (cl != null) return cl;
        ClassLoader own = PulseLoggingEnvironmentPostProcessor.class.getClassLoader();
        return (own != null) ? own : ClassLoader.getSystemClassLoader();
    }
}
